name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv venv
        uv pip install nox
        uv pip install -e ".[dev,tests]"

    - name: Run linting
      run: nox -s lint

    - name: Run formatting check
      run: nox -s format_code

    - name: Run type checking
      run: nox -s typing

    - name: Run tests
      run: nox -s test

    - name: Run security checks
      run: nox -s security

  docs:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv pip install nox
        uv pip install -e ".[docs]"

    - name: Build documentation
      run: nox -s docs
